variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Djavax.xml.accessExternalSchema=all"
  MYSQL_DB: javaee_test
  MYSQL_USER: Math
  MYSQL_PASSWORD: Math10081994
  MYSQL_ROOT_PASSWORD: Lineos10081994

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test

validate:jdk8:
  stage: build
  script:
    - cd biblio-ws
    - 'mvn $MAVEN_CLI_OPTS test-compile'
  image: maven:3.5.0-jdk-8

deploy:jdk8:
  stage: test
  services:
    - mysql:latest
  before_script:
    - apt-get update -q && apt-get install -qqy --no-install-recommends mysql-client
  script:
    - cd biblio-ws
    - mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h localhost < GRANT ALL ON javaee_test.* TO '$MYSQL_USER'@'%';
    - 'mvn $MAVEN_CLI_OPTS -Ptest verify'
  image: maven:3.5.0-jdk-8