version: '3.1'
services:
  myerp.db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
       - "./init/db_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=Lineos10081994
      - MYSQL_DATABASE=javaee
      - MYSQL_USER=Math
      - MYSQL_PASSWORD=Math10081994

  myerp2.db:
      image: mysql:5.7
      ports:
        - "3307:3306"
      volumes:
        - "./init/db_test/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
      environment:
        - MYSQL_ROOT_PASSWORD=Lineos10081994
        - MYSQL_DATABASE=javaee_test
        - MYSQL_USER=Math
        - MYSQL_PASSWORD=Math10081994
      
